# Namespace
---
kind: Namespace
apiVersion: v1
metadata:
  name: vehicleregistration-namespace
  labels:
    app: vehicleregistration

# Deployment
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: vehicleregistration-deployment
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/part-of: vehicleregistration
    app: vehicleregistration
  name: vehicleregistration
  namespace: vehicleregistration-namespace
spec:
  replicas: 1 # change to 2+ on real deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1  
  selector:
    matchLabels:
      app: vehicleregistration
  template:
    metadata:
      labels:
        app: vehicleregistration
    spec:
      containers:
        - name: vehicleregistration
          #image: vehicleregistrationservice:0.13
          image: ghcr.io/madhon/vehicleregistrationservice:latest
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            failureThreshold: 30
            periodSeconds: 10          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 2000
            #fsGroup: 2000
            allowPrivilegeEscalation: false
            privileged: false
            #readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1028Mi"

# Service
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: vehicleregistration-service
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/part-of: vehicleregistration
  name: vehicleregistration
  namespace: vehicleregistration-namespace  
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: vehicleregistration

# ingress
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: vehicleregistration-ingress
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/part-of: vehicleregistration  
  name: vehicleregistration-ingress
  namespace: vehicleregistration-namespace
  annotations:
spec:
  #ingressClassName: traefik
  rules:
    - host: vehicle-127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vehicleregistration
                port:
                  number: 80