kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}-deployment
    app.kubernetes.io/version: "{{ .Values.image.version }}"
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values.strategy.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
#      annotations:
#        dapr.io/enabled: "true"
#        dapr.io/app-id: "vehicleregistration"
#        dapr.io/app-port: "80"
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.image.pullpolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            privileged: false
            #readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all             
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          resources:
            requests:
              cpu: "{{ .Values.hpa.cpuRequests }}"
