kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}-hpa
    app.kubernetes.io/version: "{{ .Values.image.version }}"
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCpuPercent }}