kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}-ingress
    app.kubernetes.io/version: "{{ .Values.image.version }}"
    app.kubernetes.io/part-of: {{ .Values.appName }}  
  name: {{ .Values.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: {{ .Values.image.port }}