name: "DevSecOps Analysis"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  HUSKY : 0
  
permissions: read-all

jobs:
  analyze:
    name: DevSecOps
    runs-on: ubuntu-24.04
    if: github.actor!= 'depbot'   # ignore the pull request which comes from user depbot.    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v5

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo

    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
        
    - name: Upload alerts artifact
      uses: actions/upload-artifact@v4
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}        