name: "DevSecOps Analysis"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions: read-all

jobs:
  analyze:
    name: DevSecOps
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1.12.0
      id: msdo

    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3.28.1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
        
    - name: Upload alerts artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}        