name: "DevSecOps Analysis"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  HUSKY : 0
  
permissions: read-all

jobs:
  analyze:
    name: DevSecOps
    runs-on: ubuntu-24.04
    if: github.actor!= 'depbot'   # ignore the pull request which comes from user depbot.    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@5b26a185ff02cf7c100778adeff0ebbf704ca144 # v1
      id: msdo

    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
        
    - name: Upload alerts artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}        