name: Docker Build & Publish to ghcr.io

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*' ]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vehicleregistrationservice
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          conext: vehicleregistrationservice
          push: true
          tags: ghcr.io/madhon/vehicleregistrationservice:latest
